import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import fs from 'fs'
import path from 'path'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const order = await db.order.findUnique({
      where: { id: params.id },
      include: {
        payment: true,
        cardDesign: true
      }
    })

    if (!order) {
      return NextResponse.json(
        { message: 'Order not found' },
        { status: 404 }
      )
    }

    // Generate simple text-based invoice
    const invoice = `
============================================
              SKY ZONE
          Premium PVC ID Cards
============================================

INVOICE

Invoice Number: ${order.orderNumber}
Date: ${new Date().toLocaleDateString()}
Payment ID: ${order.payment?.razorpayPaymentId || 'N/A'}

============================================
BILL TO
============================================
Name: ${order.customerName}
Email: ${order.customerEmail}
Phone: ${order.customerPhone}
${order.customerAddress ? `Address: ${order.customerAddress}` : ''}

============================================
ORDER DETAILS
============================================
Card Type: ${order.cardDesign.name}
Quantity: ${order.quantity}
Price per card: ₹${order.pricePerCard}

============================================
TOTAL
============================================
Total Amount: ₹${order.totalPrice.toFixed(2)}
Payment Status: ${order.payment?.status.toUpperCase() || 'N/A'}

============================================
Thank you for your order!

For queries:
Email: support@skyzone.com
Phone: +91 98765 43210

============================================
Generated by Sky Zone
============================================
    `.trim()

    return new NextResponse(invoice, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="invoice-${order.orderNumber}.txt"`
      }
    })
  } catch (error) {
    console.error('Download invoice error:', error)
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    )
  }
}
